input[int p, string q]
output[int k]

fsm hello {
       
        ~ This will fail becuase k is output var and not allowed to be accessed from SAKE only set 
	state Hello
                if (k == 1) {
                        printf("%s", "Hello ")
                        goto World
                }
                else {
                        goto Hello
                }
        state World
                if (p == 1) {
                        printf("%s%s\n", q, "'s World")
                        goto Hello
                }
                else {
                        goto World
                }
}
