input[int p, string q]
output[int k]

fsm hello {
        int x = 4
        
	state Hello
                if (p == 1) {
                        printf("%s", "Hello ")
                        x = 'e'
                        goto World
                }
                else {
                        goto Hello
                }
        state World
                if (p == 1) {
                        printf("%s%s\n", q, "'s World")
                        goto Hello
                }
                else {
                        goto World
                }
}
