input[int p, string q]
output[int k]

fsm hello {
        int x = 6
        char y = 9 
 
	state Hello
                if (p == 1) {
                        printf("%s", "Hello ")
                        x = x / y
                        goto World
                }
                else {
                        goto Hello
                }
        state World
                if (p == 1) {
                        printf("%s%s\n", q, "'s World")
                        goto Hello
                }
                else {
                        goto World
                }
}
