input [int i]
output [int o]

fsm fsmhello {
	start s0{
		o = 0
		if (i==0){
			goto s0
		}
		else
			goto s1
	}
	s1{
		o = 1
		if (i==0){
			goto s1
		}
		else
			goto s2
	}
	s2{
		o = 2
		if (i==0){
			goto s2
		}
		else
			goto s3
	}
	s3{
		o = 3
		if (i==0){
			goto s3
		}
		else
			goto s4
	}
	s4{
		o = 4
		if (i==0){
			goto s4
		}
		else
			goto s5
	}
	s5{
		o = 5
		if (i==0){
			goto s5
		}
		else
			goto s6
	}
	s6{
		o = 6
		if (i==0){
			goto s6
		}
		else
			goto s7
	}
	s7{
		o = 7
		if (i==0){
			goto s7
		}
		else
			goto s8
	}
}
=======
input = [int i]
output = [string o]

fsm f1{
	start s0{
		o = "zero"
		switch (i){
			case 0: goto s0
			case 1: goto s1
		}
	}

	s1{
		o = "one"
		switch (i){
			case 0: goto s1
			case 1: goto s2
		}
	}

	s2{
		o = "two"
		switch (i){
			case 0: goto s2
			case 1: goto s3
		}
	}

	s3{
		o = "three"
		switch (i){
			case 0: goto s3
			case 1: goto s4
		}
	}

	s4{
		o = "four"
		switch (i){
			case 0: goto s4
			case 1: goto s5
		}
	}

	s5{
		o = "five"
		switch (i){
			case 0: goto s5
			case 1: goto s6
		}
	}

	s6{
		o = "six"
		switch (i){
			case 0: goto s6
			case 1: goto s7
		}
	}

	s7{
		o = "seven"
		switch (i){
			case 0: goto s7
			case 1: goto s8
		}
	}
}
