input[int i]
output[char out] 

fsm trafficLight {
	 state red
                if (i == 1) {
                        out = 'g' 
                        goto green
                }
                else {
                        out = 'r'
                        goto red
                }
        state yellow
                out = 'r' 
                goto red 
        state green
                if (i == 0) {
                        out = 'y'
                        goto yellow
                }
                else {
                        out = 'g'
                        goto green
                }    
}
