input[int i, int o]
output[int k, int l]

type Test = One | Two | Three

fsm one {
        public int j = 4
        ~ int r = two.k 

        state emma 
                goto shalva
        state shalva
                goto emma
}
fsm two {
        public int f = 3
        
	state kz 
                f = 45
}
fsm three {
        public int k = 4
        int f = 24
        int z = 2

        state ac
               z = 35 
}
fsm four {       
      int t = 132124
      int s = 123123

} 
fsm five {

}
fsm six {

        state yay 
                goto yay
}
