input[int inOne, int inTwo]
output[char outOne, char outTwo] 

fsm tlOne {
        
	state R1
                if (inOne == 1) {
                        outOne = 'g' 
                        goto G1
                }
                else {
                        outOne = 'r'
                        goto R1
                }
        state Y1
                outOne = 'r'
                goto R1
        state G1
                if (inOne == 0) {
                        outOne = 'y'
                        goto Y1 
                }
                else {
                        outOne = 'g'
                        goto G1
                }    
}
fsm tlTwo {
 
       state R2
                if (inTwo == 1) {
                        outTwo = 'g' 
                        goto G2
                }
                else {
                        outTwo = 'r'
                        goto R2
                }
        state Y2
                outTwo = 'r'
                goto R2
        state G2
                if (inTwo == 0) {
                        outTwo = 'y'
                        goto Y2 
                }
                else {
                        outTwo = 'g'
                        goto G2
                }    
}
