input[int i]
output[char k] 

fsm trafficLight {
        state Red
                if (i == 1) {
                        k = 'y' 
                        goto Yellow
                }
                else {
                        k = 'r'
                        goto Red
                }
        state Yellow
                if (i == 1) {
                        k = 'g'
                        goto Green 
                } 
                else {
                        k = 'y'
                        goto Yellow
                }
        state Green
                if (i == 1) {
                        k = 'r'
                        goto Red 
                }
                else {
                        k = 'g'
                        goto Green
                }    
}
