input[int inTwo]
output[char outOne, char outTwo] 

fsm tlOne {
        public int turnOne = 1        
        int count = 0
        
        state r1
                if (tlTwo.turnTwo == 1) {
                        outOne = 'r'
                        count = 0
                        goto r1
                }
                else {        
                        if (count < 1) { 
                                count = count + 1
                                outOne = 'r'
                                goto r1
                        }
                        count = 0
                        outOne = 'g'
                        goto g1    
                }    
        state y1               
                outOne = 'r'
                count = 0
                goto r1
        state g1
                if (tlTwo.turnTwo == 0) {
                        outOne = 'g'
                        goto g1
                }
                outOne = 'y'
                goto y1 
}
fsm tlTwo {
        public int turnTwo = 0 
        int count = 0 
        
        state r2
                if (inTwo == 1) {
                        turnTwo = 1
                }
                if (turnTwo == 1 && tlOne == r1) {
                        outTwo = 'g' 
                        count = 0 
                        goto g2
                }
                else {
                        outTwo = 'r'
                        goto r2
                }
        state y2
                outTwo = 'r'
                turnTwo = 0
                goto r2
        state g2
                while (count < 10) {
                        count = count + 1
                        outTwo = 'g'
                        goto g2
                } 
                outTwo = 'y'
                goto y2 
}
